### ISSUE TITLE
Dynamic cursor

### ISSUE THREAD

**Issue by bnhardy** [dyedgreen/juniper-relay#1]
First, I love what the crate can do.  However, I would like the option of setting the cursor dynamically in RelayConnection::new().  If I set the cursor to a combination of the primary key and one or more order_by fields, that may change depending on the input parameters for the query.

**Comment by dyedgreen** [comment]
You can simply make a new-type that implements the connection node trait and has a custom cursor; something like:

```rust
struct MyNode {
  cursor: String, // or a tuple of your parameters
  node: TheThing,
}
```
